"""empty message

Revision ID: 035aa8d5cc92
Revises: d297acb6c2de
Create Date: 2026-03-17 19:46:56.343043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035aa8d5cc92'
down_revision = 'd297acb6c2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
