"""empty message

Revision ID: 2f51b0033380
Revises: 762558271554
Create Date: 2026-02-19 22:40:50.922209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f51b0033380'
down_revision = '762558271554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=False))
        batch_op.drop_column('contact_method')
        batch_op.drop_column('name')
        batch_op.drop_column('contact_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_method', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('subject')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
