"""empty message

Revision ID: 4a68d489db47
Revises: 0a143dfa97f5
Create Date: 2026-03-10 21:08:00.782541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a68d489db47'
down_revision = '0a143dfa97f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('gallery_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_type', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
