"""empty message

Revision ID: a9ae7809f269
Revises: 4a68d489db47
Create Date: 2026-03-11 02:54:11.331615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9ae7809f269'
down_revision = '4a68d489db47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ministry',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('ministry',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
